const JELLY_IMAGES=['/jelly/jelly_blue.png','/jelly/jelly_pink.png','/jelly/jelly_green.png','/jelly/jelly_yellow.png','/jelly/jelly_puple.png','/jelly/jelly_grey.png'];
const HATS={partyhat:'🥳',crown:'👑',ribbon:'🎀',beret:'🧢'};const EXPRESSIONS={smile:'⌒‿⌒',heart:'♥  ♥',sleepy:'－ －',wink:'◕  ‿'};
function Jelly({colorIndex=0,size=1,float=false,hat='',effect='',expression='normal',accessory='',color=''}){const width=Math.round(90*size);const marks=effect==='sparkles'?['✨','✦','✨']:effect==='bubbles'?['◌','○','◦']:effect==='flowers'?['🌸','✿','🌸']:effect==='gold'||color==='gold'?['✨','✧','✨']:[];return <div style={{position:'relative',display:'inline-block',width,animation:float?'jellyFloat 2.8s ease-in-out infinite':undefined,filter:(effect==='gold'||color==='gold')?'drop-shadow(0 0 10px rgba(245,158,11,.45))':undefined}}>
<img src={JELLY_IMAGES[colorIndex]||JELLY_IMAGES[0]} alt="해파리" draggable={false} style={{width:'100%',display:'block',pointerEvents:'none'}}/>
{hat&&HATS[hat]&&<span style={{position:'absolute',top:'-22%',left:'50%',transform:'translateX(-50%)',fontSize:28*size,lineHeight:1}}>{HATS[hat]}</span>}
{accessory==='scarf'&&<span style={{position:'absolute',bottom:'-4%',left:'50%',transform:'translateX(-50%)',fontSize:24*size}}>🧣</span>}
{expression!=='normal'&&EXPRESSIONS[expression]&&<span style={{position:'absolute',left:'50%',top:'42%',transform:'translate(-50%,-50%)',fontSize:11*size,fontWeight:900,color:'#184B70',background:'rgba(232,247,255,.72)',padding:'2px 5px',borderRadius:999,whiteSpace:'nowrap'}}>{EXPRESSIONS[expression]}</span>}
{marks.map((m,i)=><span key={i} style={{position:'absolute',fontSize:(13+i*2)*size,left:i===0?'-10%':i===1?'83%':'65%',top:i===0?'18%':i===1?'5%':'76%',animation:'jellyFloat 2.2s ease-in-out infinite'}}>{m}</span>)}</div>}
export{JELLY_IMAGES};export default Jelly;
